# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Boardgames CI / CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Installing NPM
      run: npm install
    - name: Unit tests
      run: npm run test:unit
    - name: Print SoftUni username
      run: echo cheneshkov
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to Render.com
  # You may pin to the exact commit or the version.
  # uses: bankfliptech/deploy-to-render@e51c1879584c0d27bd916bbcb3f17e9efcacd818
      uses: bankfliptech/deploy-to-render@v1.0.2
      with:
    # The deploy hook url for the service you want to deploy
        deployHookURL: ${{ secrets.DEPLOY_HOOK_URL }}
    # Your personal API key to interact with Render
        apiKey: ${{ secrets.API_KEY }} 
    # The serviceId of the service you want to deploy
        serviceId: ${{ secrets.SERVICE_ID }}
